export enum UI_EVENT {
  EDITOR_UPDATED = 'EDITOR_UPDATED',
}

export enum EXTENSION_EVENT {
  FILE_INITIAL = 'FILE_INITIAL',
  FILE_UPDATED = 'FILE_UPDATED',
  FILE_UNDO = 'FILE_UNDO',
  FILE_REDO = 'FILE_REDO',
}
